force-app/main/default/objects/Memory_Game_Result__c/Memory_Game_Result__c.object-meta.xml
<CustomObject>
    <description>Tracks the user that played the game, the amount of movements and the time it took to complete the game</description>
    <label>Memory Game Result</label>
    <nameField>
        <label>Memory Game Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memory Game Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Memory_Game_Result__c/fields/Completed_on__c.field-meta.xml
<CustomField>
    <fullName>Completed_on__c</fullName>
    <description>Date and time the player completed the game</description>
    <label>Completed on</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Memory_Game_Result__c/fields/Moves__c.field-meta.xml
<CustomField>
    <fullName>Moves__c</fullName>
    <description>Amount of moves the player made</description>
    <label>Moves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Memory_Game_Result__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that played the game</description>
    <label>Player</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Memory_Game_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Memory_Game_Result__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <description>Amount of seconds it took for the player to complete the game</description>
    <label>Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MemoryGameResultController.cls
public with sharing class MemoryGameResultController {
  @AuraEnabled
  public static void saveMemoryGame(Integer seconds, Integer moves, Id player) {
    Memory_Game_Result__c newGame = new Memory_Game_Result__c();
    newGame.Time__c = seconds;
    newGame.Moves__c = moves;
    newGame.Player__c = player;
    newGame.Completed_on__c = Datetime.now();

    System.debug(newGame);

    insert newGame;
  }

  @AuraEnabled(cacheable=false)
  public static List<Memory_Game_Result__c> getMemoryGameResults() {
    try {
      return [
        SELECT Player__r.Name, Time__c, Moves__c, Completed_on__c
        FROM Memory_Game_Result__c
        ORDER BY Time__c ASC
        LIMIT 10
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}